version: "3.1"

services:
  oraclesql:
    image: container-registry.oracle.com/database/enterprise
    container_name: oracle-sql1
    ports:
      - 1521:1521
    environment:
      ORACLE_SID: Respawn
      ORACLE_PDB: Respawn1
      ORACLE_PWD: PasswordO1.
    volumes:
      - ./env/oracle/setup:/docker-entrypoint-initdb.d/setup:ro